### ISSUE TITLE
broken?

### ISSUE THREAD

**Issue by alick-at-ghost** [snehankekre/streamlit-selenium-chrome#2]
app seems to be broken

AttributeError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).

**Comment by snehankekre** [comment]
Hi @alick-at-ghost 👋 

Thank you for reporting this issue! I confirmed the error occurred due to a mismatch between the app code versus the version of the webdriver_manager used.

I've [updated](https://github.com/snehankekre/streamlit-selenium-chrome/compare/f4e7aa4341f76909400e3992ff485f3c3d4d9745..e4109a5e1959497c958244c8c964b1db48c88df3) the app to use the latest webdrive_manager API, and it now runs without errors on Community Cloud.
